### ISSUE TITLE
Investigate compatibility with Orleans v4 preview

### ISSUE THREAD

**Issue by jeremylcarter** [OrleansContrib/Orleans.Providers.MongoDB#100]
I think we should investigate compatibility with the breaking changes coming in Orleans v4.

I have forked the repository and will see what work is involved.

**Comment by jeremylcarter** [comment]
I have done the major legwork to target .NET Core 3.1 and Orleans v4.

https://github.com/jeremylcarter/Orleans.Providers.MongoDB/tree/feature/orleans_v4

**Comment by SebastianStehle** [comment]
Thanks for your work.

Many important test classes are not available as nuget package, therefore I just built Orleans myself and added everything to the libs folder.

Created a PR for that: https://github.com/dotnet/orleans/issues/7817

**Comment by jeremylcarter** [comment]
Oh I see! So I just need to get the latest of those classes and compile
them?

**Comment by SebastianStehle** [comment]
Yes, exactly. it sucks, but I think it is better than writing these tests manually.

**Comment by jeremylcarter** [comment]
It wasn't a big deal upgrading, I quite enjoyed it.

**Comment by jeremylcarter** [comment]
@SebastianStehle I will need some help getting the tests organized.

**Comment by SebastianStehle** [comment]
How is it going?

**Comment by SebastianStehle** [comment]
In the current branch the tests were actually not running. I fixed that.

**Comment by jeremylcarter** [comment]
I'll sort out a branch this week and collaborate with you if you're keen. Thanks.

**Comment by MarkusGeigerDev** [comment]
How are things going, folks? I also had a quick look and made quite a progress after yesterdays release of Orleans 7 but then I stumbled across the same issue with the ./libs.
@jeremylcarter: Should we work together to get this up and running for Orleans 7? I would even considering stepping in as a (co-)maintainer for this package.

**Comment by SebastianStehle** [comment]
> How are things going, folks? I also had a quick look and made quite a progress after yesterdays release of Orleans 7 but then I stumbled across the same issue with the ./libs.

We could just use a git submodule and import the necessary project files into the solution.

> I would even considering stepping in as a (co-)maintainer for this package.

I am not using Orleans anymore so I would really appreciate that.

**Comment by MarkusGeigerDev** [comment]
> We could just use a git submodule and import the necessary project files into the solution.
Good idea. Could you help to prepare that? 

> > I would even considering stepping in as a (co-)maintainer for this package.
> 
> I am not using Orleans anymore so I would really appreciate that.
Yeah, I read about that in the other issue. I'm on the other hand am just getting deeper into it and I am definitely interested in keeping the MongoDB support alive :)

**Comment by SebastianStehle** [comment]
> Good idea. Could you help to prepare that?

I can have a look, but I guess it would be a good first issue for you as well ;) ... 

so

1. Import libs from submodule
2. Create 3.X branch
3. Work on 4.X migration

**Comment by jeremylcarter** [comment]
Did you want to catch up? I'll push up my branch.

**Comment by jeremylcarter** [comment]
My branch is here:

jeremylcarter/Orleans.Providers.MongoDB at feature/orleans_v4 (github.com)
<https://github.com/jeremylcarter/Orleans.Providers.MongoDB/tree/feature/orleans_v4>

Commits:

Comparing OrleansContrib:master...jeremylcarter:feature/orleans_v4 ·
OrleansContrib/Orleans.Providers.MongoDB (github.com)
<https://github.com/OrleansContrib/Orleans.Providers.MongoDB/compare/master...jeremylcarter:Orleans.Providers.MongoDB:feature/orleans_v4>

**Comment by SebastianStehle** [comment]
Just create a PR and I can help and review

**Comment by MarkusGeigerDev** [comment]
> My branch is here: jeremylcarter/Orleans.Providers.MongoDB at feature/orleans_v4 (github.com) 
Thanks!
I'm looking through your changes and comparing them to mine. It seems like there were a few breaking changes between v4-rc and v7 and I'm trying to kind of merge what you did with my changes. I suggest that I will push my branch when I'm ready and then let's decide what to bring forward as a PR.

**Comment by MarkusGeigerDev** [comment]
@jeremylcarter 
Here's my port: https://github.com/MarkusGeigerDev/Orleans.Providers.MongoDB/tree/Orleans_v7
I still didn't get the unit tests to work - I will probably try Sebastian's suggestion with the submodules later

**Comment by SebastianStehle** [comment]
I have created a PR to visualize the changes.

**Comment by MarkusGeigerDev** [comment]
BTW: I followed these guidelines and hints: https://learn.microsoft.com/en-us/dotnet/orleans/whats-new-in-orleans
