### ISSUE TITLE
Now i have _doc as inner property.   i am want to have all internal properties on top level (as columns)

### ISSUE THREAD

**Issue by P9avel** [OrleansContrib/Orleans.Providers.MongoDB#101]
I am want save all without _doc property. How to do it?

![Безымянный](https://user-images.githubusercontent.com/95086762/182030332-fea0c1b2-3ed5-4851-a9db-fe4ab8755f94.png)

**Comment by SebastianStehle** [comment]
It is not possible or not easily possible:

Somehow you have to create a object and you have the following properties from Orleans:

* Key
* Etag
* Value

First of all the value could be a primitive, like string, but even if it would be a document it would be tricky to convert it to a flat document. Lets say you have the following value

```
class MyValue
{
   [JsonProperty("_id")]
   public string Id {get; set; }
}
```

Then your Id would overlap with the mongodb _id which is basically the grain identity and you would have a conflict here. It is not worth to handle these details. For MongoDB it does not really matter and you can get a better Management Tool like Studio3T.

**Comment by P9avel** [comment]
Many thanks for quick answer. I am understood now
