### ISSUE TITLE
How to tuning WriteConcern value?

### ISSUE THREAD

**Issue by P9avel** [OrleansContrib/Orleans.Providers.MongoDB#102]
I am used MongoDB.Driver and tuned so database.GetCollection<T>(GetCollectionName())                                           .WithWriteConcern(GetCollectionWriteConcern());

How to turn in Orleans.Providers.MongoDB?

**Comment by SebastianStehle** [comment]
I added this property to the options: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/master/Orleans.Providers.MongoDB/Configuration/MongoDBOptions.cs#L37

**Comment by P9avel** [comment]
When you released new version?

**Comment by SebastianStehle** [comment]
it has been released as 3.8
