### ISSUE TITLE
Support for BSON Serializer

### ISSUE THREAD

**Issue by wassim-k** [OrleansContrib/Orleans.Providers.MongoDB#106]
Currently, this provider only supports using Json.NET for serializing grain state to MongoDB.  
It would be great to support the option to use BSON Serializer shipped with mongodb driver instead, since it has great documentation, support and many features that are specific for mongo db storage.

For example a more generic interface like this one might serve the purpose:
```csharp
public interface IMongoGrainStorageSerializer
{
    void Deserialize<T>(IGrainState<T> grainState, BsonDocument document);

    BsonDocument Serialize<T>(IGrainState<T> grainState);
}
```

Current implementation can be achieved with something like this:
```csharp
public class MongoGrainStateSerializer : IMongoGrainStorageSerializer
{
    private readonly IGrainStateSerializer _serializer;

    public MongoGrainStateSerializer(IGrainStateSerializer serializer)
    {
        _serializer = serializer;
    }

    public void Deserialize<T>(IGrainState<T> grainState, BsonDocument document)
    {
        _serializer.Deserialize(grainState, document.ToJToken());
    }

    public BsonDocument Serialize<T>(IGrainState<T> grainState)
    {
        var jObj = _serializer.Serialize(grainState);
        return jObj.ToBson();
    }
}
```

And finally using BSON Serializer can be done like this:
```csharp
public class MongoBsonGrainStorageSerializer : IMongoGrainStorageSerializer
{
    public void Deserialize<T>(IGrainState<T> grainState, BsonDocument document)
    {
        grainState.State = BsonSerializer.Deserialize<T>(document);
    }

    public BsonDocument Serialize<T>(IGrainState<T> grainState)
    {
        return BsonDocumentWrapper.Create(grainState.State);
    }t
}
```

The one issue I can see with using BSON Serialize is the lack of support for some Json.NET Converters that are implemented by Orleans, but I believe it wouldn't be too difficult to implement those converters using BSON Serializer, and I'd gladly contribute that work to your repo if you're happy with this feature suggestion.

**Comment by SebastianStehle** [comment]
The serializer already exists, but is coupled to json now. Should be easy to change it return BsonDocument now.

But I would probably go with BsonValue instead of BsonDocument to support scalars line `int`, `string and so on. Do you want to provide a PR for that?

**Comment by wassim-k** [comment]
Is it okay to introduce a breaking change by changing the current definition of `IGrainStateSerializer`?

**Comment by SebastianStehle** [comment]
For 4.0...yes

**Comment by wassim-k** [comment]
Sounds good, once the 4.0 changes are merged, I'll raise a PR for this.

**Comment by SebastianStehle** [comment]
Great. I am not planning any migration before Orleans 4.0 is released. So nothing for prereleases.

**Comment by wassim-k** [comment]
Just a heads up, the work on this is already done, let me know when it's time to merge it into the 7.0 migration.
