### ISSUE TITLE
Reminders after silo restart

### ISSUE THREAD

**Issue by frfly** [OrleansContrib/Orleans.Providers.MongoDB#117]
Hello!

There is an issue, when using MongoDb as storage for reminders. When you create reminder, [it has](https://github.com/dotnet/orleans/blob/535290fbb7fa6dfca059cc94bc8cd6e4426f37f3/src/Orleans.Reminders/ReminderService/LocalReminderService.cs#L127) `DateTimeKind.Utc` . But when you restart silo, reminder entry [restores with ](https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/master/Orleans.Providers.MongoDB/Reminders/Store/MongoReminderDocument.cs#L34)  `DateTimeKind.Unspecified` . So if you have, e.g., timezone GMT+3, you`ll have to wait for additional three hours until reminder start.

It was fixed [here](https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/91), but then rolled back.

**Comment by MarkusGeigerDev** [comment]
Hi @frfly, thanks for investigating this! Do you think you can post a pull request? I'll be happy to review it next week.
Thanks and happy new year! 
M.

**Comment by SebastianStehle** [comment]
Somehow the fix did not comply with the tests. Therefore it was reverted.

**Comment by wassim-k** [comment]
Yeh, I saw your comment @SebastianStehle on the other thread, I'll try and have a look at this tonight.
