### ISSUE TITLE
Method Not Found on GrainReference.FromKeyString

### ISSUE THREAD

**Issue by asifshiraz** [OrleansContrib/Orleans.Providers.MongoDB#12]
Hi,

I'm getting an error when using this library for Orleans reminders.

It throws an error on line 101 in MongoReminderTableRepository.cs, saying that Method not found.
It seems to be calling GrainReference.FromKeyString, which is an internal method in Orleans library.
Any suggestions?

**Comment by laredoza** [comment]
Hi,

Could you please supply your package,json (related to Orleans). I haven't upgraded the Orleans libraries in a while, something may have changed. Do you experience the same issue in the test project?

From my side I will upgrade my project libraries to see if I can recreate it.

**Comment by laredoza** [comment]
![image](https://user-images.githubusercontent.com/5489412/27485963-388ecc6a-582f-11e7-9be0-a5176057d1bf.png)

**Comment by laredoza** [comment]
This seems to be an issue introduced in v1.5. I have asked for help on the main project. 

https://github.com/dotnet/orleans/issues/3162

**Comment by laredoza** [comment]
@asifshiraz, There is a new package which fixes this issue. Let me know if you have any other issues.

**Comment by laredoza** [comment]
I'm going to close this issue now. If there are any other issues please let me know.
