### ISSUE TITLE
Possibility to customize collection name instead of grain name

### ISSUE THREAD

**Issue by confluencedevelopment** [OrleansContrib/Orleans.Providers.MongoDB#13]
I am thinking if instead of going by the default of grainName.split('.').Last(), we could provide a resolver function for MongoDBStorage Provider? I am not entirely clear on how to go about it though. 
The motivation for this came up when using this on a test project that I have and I realized that I would have liked the state of one of my grains to be a in a collection based on a readonly property on the grain. I don't know if it is worth it, but thinking out aloud.

**Comment by laredoza** [comment]
Hi @confluencedevelopment  I'll have a look at it this weekend. Can't think of a quick solution at the moment.

**Comment by laredoza** [comment]
@confluencedevelopment, I suspect when https://github.com/dotnet/orleans/issues/2626 is implemented we would be able to customise the collection names. We could pass a custom GrainStateMongoDataManager provider. Maybe add two virtual methods which are called in the read and write methods to change names. We could just inherit this class and overwrite these methods.

They don't specifically mention the storageprovider but I suspect it should probably work.

What do you think?

**Comment by sujesharukil** [comment]
Just read through that. Looks like they are talking in general about providers and configurations. Might help at that time. They are talking about 2.0 though. Isn't that a long time away?

**Comment by laredoza** [comment]
Ah, sorry about that, thought it applied to 1.5 as well. Back to square one I guess. Let me investigate further.

**Comment by laredoza** [comment]
Hi @confluencedevelopment  & @sujesharukil  please check the commit. I've basically added a virtual procedure:

`
public virtual IJSONStateDataManager ReturnDataManager(string database, string connectionString)
{
        return new GrainStateMongoDataManager(database, connectionString);
}
` 

This can be overwritten:

`
public override string ReturnGrainName(string grainType)
{
      return string.Concat("OrleansStorage", base.ReturnGrainName(grainType));
}
`

to activate this new provider: 
OrleansConfiguration.xml

`
      <Provider Type="Orleans.Providers.MongoDB.Test.Host.CustomStorageProvider.MongoDBStorageWithOrleansPrefix" Name="MongoDBStore" Database="" ConnectionString="mongodb://admin:pass123@localhost:27017/Orleans?authSource=admin" />
`

Be sure to disable the default provider.

Does this achieve what you wanted to do? Do we need to add any more parameters to ReturnGrainName? 

Once everybody is happy I'll update the package.

**Comment by laredoza** [comment]
Due to fixing compatibility issues with Orleans 1.5 this has been released.

**Comment by confluencedevelopment** [comment]
This will work, but can the method actually pass in the "grainReference" too and not just the grainType?

**Comment by laredoza** [comment]
That should be possible, I'll implement this weekend.

**Comment by sujesharukil** [comment]
Thanks.

**Comment by sujesharukil** [comment]
Just looked at the commit. I was hoping you pass the grain reference instead of the grain state into resolving the collection name. Reason being that the first time a grain is activated the grain state is going to be default and nothing can be used from it to determine the name of the collection.

**Comment by laredoza** [comment]
I suspect it should be possible. I'll have a look

**Comment by laredoza** [comment]
@sujesharukil, I'm passing the grain reference now. Please have a look and let me know if you need anymore changes.

**Comment by sujesharukil** [comment]
This looks good. Don't think grain state will buy you anything

**Comment by laredoza** [comment]
@sujesharukil, I'm probably going to only release a new nuget package end of the week / next week as I'm busy refactoring a lot of the queries. I used AsQuery calls instead of the findAsync method in my queries which will cause blocking. This is going to require a bit of testing but should get us closer to production ready. I've completed the membership & reminders providers. I still have to finish

**Comment by sujesharukil** [comment]
sounds good @laredoza .. I am waiting for a release.

**Comment by laredoza** [comment]
@sujesharukil and @confluencedevelopment  Package Orleans.Providers.MongoDB 0.1.1 has been released with these changes.

**Comment by sujesharukil** [comment]
Great! I will take a look. Thanks.

**Comment by sujesharukil** [comment]
This is verified and works as expected. Thanks

**Comment by laredoza** [comment]
Thanks @sujesharukil
