### ISSUE TITLE
MongoDB 3.0.0 support

### ISSUE THREAD

**Issue by neshcodes** [OrleansContrib/Orleans.Providers.MongoDB#139]
Removing MongoDB.Driver.Legacy package
Removing MongoDB.Driver.Core package
when proj`s MongoDB  upgrade => 3.0.0 , Orleans.Providers.MongoDB lose dll

**Comment by wassim-k** [comment]
Upgrade to MongoDB 3.0.0 is blocked until the [this fix](https://github.com/asimmon/ephemeral-mongo/pull/61) is merged.
