### ISSUE TITLE
General Refactor & Unit Tests

### ISSUE THREAD

**Issue by laredoza** [OrleansContrib/Orleans.Providers.MongoDB#15]
- There are quite a few things that need to be refactored. Some of the repositories contain logic which shouldn't be there. 

- Make sure that tests are working after recent changes.

- Add unit tests for Storage Provider

- Add logging to Storage Provider

- Replace AsQuery with findAsync

**Comment by laredoza** [comment]
Reminder tests are failing. Must investigate.

**Comment by sujesharukil** [comment]
May be this is a refactor or may it isn't... Noticed that in the Read of GrainStateMongoDataManager you have `existing.Remove("_id");` and in the write you are doing `doc["_id"] = existing["_id"];`. Is this required? I have Id fields in my grain state and I was using a BsonClassMap to map my class objects. This will have issues... 
So trying to understand the reason for this?

**Comment by laredoza** [comment]
@sujesharukil My Initial thought is that it's not required. I think it was in the original code this class is based off. I'll have a look this weekend.

**Comment by sujesharukil** [comment]
@laredoza did you get a chance to look at this?

**Comment by laredoza** [comment]
@sujesharukil, sorry only had a chance to look at it now. Doesn't seem as straight forward as I thought it would be:

My example object is saved as follows :
![image](https://user-images.githubusercontent.com/5489412/29134224-4df533f6-7d36-11e7-96d2-c2f8760a3483.png)

**Comment by sujesharukil** [comment]
Not sure I understand. The data you are storing is the State object and not the grain itself. The state object has an Id field and it is marked as BsonId. I think it should be more in the line that if the state object that is being saved has an "Id" attribute, then use it else let mongo create one. It can get tricky when reading whether to keep it or not. 
One option would be to enforce having an Id field in the grain state object. Another option would be to have an interface defined "IGrainStateWithId" which will enforce adding an id. You could check if the state object is of that type and if so, store the id and read it back too?

**Comment by laredoza** [comment]
@sujesharukil, Those sound like valid options, I"m just worried that the grain id needs to be passed back.

Would it be possible for you to run your application using the the standard sql  providers? I'm rather interested to compare how that is saved compared to the Mongo version (specificllly the id). I just need to establish the default behaviour before we start implementing any of these solutions. Might be that the Mongo version is completey incorrect, or that we would be breaking something else.

My time is a bit limited for the next week or so, I"ll probably only investigate further next weekend.

**Comment by sujesharukil** [comment]
We wrote our own Mongo provider and does a decent job of it. If you want to get on a call I can show what we are doing.

**Comment by laredoza** [comment]
Glad to hear that you came right @sujesharukil. I'll get hold of you on Gitter once I get a bit more time.

**Comment by laredoza** [comment]
Issue #26 completes this.
