### ISSUE TITLE
databaseName is null exception on silo start.

### ISSUE THREAD

**Issue by Xanatus** [OrleansContrib/Orleans.Providers.MongoDB#18]
I'm trying to get this package to work for MongoDB based Membership Tables in Orleans.

For my current setup, i would prefer not using Orleans config file, so I try to setup it with code like so:

```
                config.Globals.DataConnectionString = "mongodb://localhost:27017/";
                config.Globals.LivenessType = GlobalConfiguration.LivenessProviderType.Custom;
                config.Globals.MembershipTableAssembly = "Orleans.Providers.MongoDB";
                config.Globals.LivenessEnabled = true;
```

On silo startup, I'm getting this exception:

> -> System.ArgumentNullException: Value cannot be null.
> Parametername: databaseName
>    at MongoDB.Driver.Core.Misc.Ensure.IsNotNull[T](T value, String paramName)
>    at MongoDB.Driver.DatabaseNamespace..ctor(String databaseName)
>    at MongoDB.Driver.MongoClient.GetDatabase(String name, MongoDatabaseSettings
>  settings)
>    at Orleans.Providers.MongoDB.Repository.DocumentRepository..ctor(String conn
> ectionsString, String databaseName) in C:\Dev\git\Orleans.Providers.MongoDB\Orle
> ans.Providers.MongoDB\Repository\DocumentRepository.cs:Line 51.
>    at Orleans.Providers.MongoDB.Membership.MongoMembershipTable.<InitializeMemb
> ershipTable>d__4.MoveNext() in C:\Dev\git\Orleans.Providers.MongoDB\Orleans.Prov
> iders.MongoDB\Membership\MongoMembershipTable.cs:Line 37.

I'm using Orleans 1.5.1 and Orleans.Providers.MongoDB 0.1.1 (latest from Nuget).

**Comment by Xanatus** [comment]
Alright, I figured it out.
I had to provide the databaseName with the conntection string.
`config.Globals.DataConnectionString = "mongodb://localhost:27017/MembershipTable";`

Additionaly to this, setting the DeploymentID manually is also required, otherwise it will throw a "Key may not be empty." exception.

**Comment by laredoza** [comment]
Sorry, don't have access to a pc at the moment, but my connectionstrings look as follows:

mongodb://admin:pass123@localhost:27017/Orleans?authSource=admin

Have You tried to add Orleans to your connection string?

I'll have a look tomorrow at any rate. I'd like to add this to the documentation  in any case either way

**Comment by laredoza** [comment]
Okay, see my post was a bit late and don't seem to be able to edit the previous post on mobile.

I'd suggest using Orleans as the database name to keep it consistent. The membership collection should then be created in the Orleans database.

If you then use the same connectionstring with the other providers the collections will all be in the same database as well.
