### ISSUE TITLE
Support for Strong Consistency?

### ISSUE THREAD

**Issue by ReubenBond** [OrleansContrib/Orleans.Providers.MongoDB#22]
Hi, I'm curious how the storage provider here supports strong consistency for grain state.

It seems that the updates here should include a query condition, something along the lines of "version == expected version", similar to how the Azure storage providers use an ETag.

https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/3e4d3518015ce886ca046ba3f56905b218a14a47/Orleans.Providers.MongoDB/StorageProviders/GrainStateMongoDataManager.cs#L109

**Comment by laredoza** [comment]
Hi @ReubenBond, I'll have a look at the Azure implementation and get back to you on this. Probably this weekend.

**Comment by laredoza** [comment]
@ReubenBond  on an unrelated note, who can I add as an Owner for the the nuget library (https://www.nuget.org/packages/Orleans.Providers.MongoDB)? You never know when a bus decides to drive over me or something.

**Comment by SebastianStehle** [comment]
The fast approach would be to replace it with an Upsert:

    collection.ReplaceOnAsync(x => x.Id == key && x.Etag == etag, doc, new Options { Upsert = true });

There are several cases:

1. No document exits => Makes insert and adds etag
2. Document exists and has correct etag => Makes update
3. Document exists and has incorrect etag => Tries to make insert, fails with DuplicateKeyException, which can be ignored.

**Comment by laredoza** [comment]
Issue #26 implements this
