### ISSUE TITLE
vNext / 1.0

### ISSUE THREAD

**Issue by SebastianStehle** [OrleansContrib/Orleans.Providers.MongoDB#26]
## Storage Provider

- [x] Improve the performance of the StorageProvider by preventing a serialization step
- [x] Improve the performance of the StorageProvider by ensuring that we make only one call to MongoDB per operation.
- [x] Implement optimistic concurrency with backwards compatibility.
- [x] Write tests for StorageProvider (partially done)
- [x] Fix a bug with wrong naming of collections when Grain is a nested class. (in vnext branch)
- [x] Add logging.

## Statistics

- [x] Cleanup statistics
- [x] Improve statistics by ensuring that we make only one call to MongoDB per operation.
- [x] Write tests for statistics (or get them working again)
- [x] Store statistics over time not only a snapshot (I have a test in vnext branch for it).

## Reminders

- [x] Cleanup reminders
- [x] Improve reminders by ensuring that we make only one call to MongoDB per operation.
- [x ] Write tests for reminders (or get them working again)
- [x] Implement optimistic concurrency for reminders.

## Membership

- [x] Cleanup membership
- [x] Improve membership by ensuring that we make only one call to MongoDB per operation.
- [x] Write tests for membership (or get them working again)
- [x] Implement optimistic concurrency for membership, in away that only one collection is required (MongoDB is not ACID)

## General

- [x] Extend test app with  statistics
- [x] Use new configuration system.
- [ ] Check value of loggings.

**Comment by laredoza** [comment]
**Question 1**: I'd prefer to not break backwards compatibility. Without knowing the new structure, maybe on loading / deserialization, if there is an error we load it like we did previously, and then save the item in the new format again. Would that be possible? The other option is to add a version field to the document ( Our new documents could be version 2) and handle loading data appropriately. That way if we change this again it won't be a big deal.

**Question 2**:  Yes, it's for eTag support

![image](https://user-images.githubusercontent.com/5489412/32549708-1ee2ca5c-c493-11e7-8d64-0f33839d0fe4.png)

The initial providers were all based on the MSSql providers.

**Comment by SebastianStehle** [comment]
The problem is that you loose the information which version your document has. Which basically means that you have to query the document before updating, which will hurt performance. Not sure how to do it with compatibility.

**Comment by laredoza** [comment]
How will the new document look?

As an example the test application saves the EmployeeGrain as follows. How will it look now?

![image](https://user-images.githubusercontent.com/5489412/32550331-55de38dc-c495-11e7-86d6-5c0f1f177e05.png)

**Comment by SebastianStehle** [comment]
e.g. like that:

    {
       _id: "GrainReference=4edc4ec3a3f9faa17067449405e7e79f03ffffff95764fba"
       _etag: "ETAG",
       _doc: <SERIALIZED_JSON_DOC>
    }

**Comment by laredoza** [comment]
Okay, maybe the first idea would be the best way to go then. Load it expecting the new format. If we get an exception try and load it the previous method and update it. The next time it gets loaded it would work and we would have minimum performance impact. Is that feasible?

**Comment by SebastianStehle** [comment]
that should work, will add a test for it

**Comment by laredoza** [comment]
Should I look at upgrading to v2?

**Comment by SebastianStehle** [comment]
Do you want to keep the compatibility to 1.X? I think we can just make a v2 project in the same folder. Afaik the interfaces have no changed.

**Comment by laredoza** [comment]
I think we should just upgrade to TechPreview3(.Net.Core 2.0.)  TechPreview2 isn't production ready in any case. If someone is continuing with that version the nuget package 0.1.6 will be installed.

**Comment by SebastianStehle** [comment]
What is with Beta1?

**Comment by SebastianStehle** [comment]
I am not sure if they have already migrated TestSilo. My last info is that there was an issue because of appdomains

**Comment by laredoza** [comment]
My suspicion is that the nuget packages are behind. The project is referencing myget at the moment.

I think this is the latest version:

https://blogs.msdn.microsoft.com/orleans/2017/09/13/announcing-orleans-2-0-tech-preview-3/

**Comment by laredoza** [comment]
Well, I'm confused. I always thought previews came after the beta

**Comment by SebastianStehle** [comment]
Just confirmed it in the gitter channel ;)

**Comment by laredoza** [comment]
According to : https://github.com/dotnet/orleans/issues/3629 the plan is to release v2 four weeks after the beta release. That gives us two weeks and a bit. 

My suggestion is to get your changes out as 0.1.7-preview. Get some testing done. That way we don't need to worry about v2 breaking anything else. We can then create a new vnext branch using v2, which can then become 0.1.8-preview. What do you think?

**Comment by SebastianStehle** [comment]
Which changes are you talking about? The vnext branch is a little bit of chaos and solves too many problems right now.

**Comment by laredoza** [comment]
The changes on vnext after everything has stabilized.

**Comment by SebastianStehle** [comment]
In general my goal is to have a v1.0 for Orleans 2.0 because I need it for a project. 

I see the following tasks:

## Storage Provider

- [x] Improve the performance of the StorageProvider by preventing a serialization step
- [ ] Improve the performance of the StorageProvider by ensuring that we make only one call to MongoDB per operation.
- [ ] Implement optimistic concurrency with backwards compatibility.
- [ ] Write tests for StorageProvider (partially done)
- [x ] Fix a bug with wrong naming of collections when Grain is a nested class. (in vnext branch)

## Statistics

- [ ] Cleanup statistics
- [ ] Improve statistics by ensuring that we make only one call to MongoDB per operation.
- [ ] Write tests for statistics (or get them working again)
- [ ] Store statistics over time not only a snapshot (I have a test in vnext branch for it).

## Reminders

- [ ] Cleanup reminders
- [ ] Improve reminders by ensuring that we make only one call to MongoDB per operation.
- [ ] Write tests for reminders (or get them working again)
- [ ] Implement optimistic concurrency for reminders.

## Membership

- [ ] Cleanup membership
- [ ] Improve membership by ensuring that we make only one call to MongoDB per operation.
- [ ] Write tests for membership (or get them working again)
- [ ] Implement optimistic concurrency for membership, in away that only one collection is required (MongoDB is not ACID)

**Comment by laredoza** [comment]
OK great, let me know if I can help. My time is unfortunately very limited for the next week or two. I suspect you might be done by then :) Thanks for all the work

**Comment by AwsomeCode** [comment]
Isn't that our version number should match with Orleans Version?
As if any new storage feature in Orleans is supported Orleans.Providers.MongoDB.
Because Orleans other package follow this pattern.
For eg. 
https://www.nuget.org/packages/Orleans.StorageProvider.Arango/
https://www.nuget.org/packages/Microsoft.Orleans.OrleansAzureUtils/1.5.2

**Comment by SebastianStehle** [comment]
Of course, because they maintain it together

**Comment by laredoza** [comment]
I think v1 is fine for now. We can then create an issue on the main project for a code review.if they like it, it can then be put in the main project.

I think with the release of Orleans v2,  Mongo will become a larger part of the market as Linux adoption increases.

**Comment by AwsomeCode** [comment]
As we already support Membership, Storage, Reminders, and etc. we should push to same version 1.5.2.

**Comment by SebastianStehle** [comment]
The version should not indicate compatibility to orleans, but has an internal meaning. E.g. with Semantic Version the data format could change between v1 and v2.

**Comment by SebastianStehle** [comment]
@laredoza Can you review the storage provider?

**Comment by SebastianStehle** [comment]
@laredoza I  updated the membership provider. I think there is no way to implement the extended protocol in a reliable way, because it requires multi-document transactions. Therefore I have removed the code for the table version and only implemented etag support. It is described here and implemented for DynamoDb in the same way: https://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Cluster-Management.html

**Comment by SebastianStehle** [comment]
@laredoza I am (almost) done. What is pending is to update the Test Application. I have imported the TesterInternals assembly from Orleans to run their tests and found some bug (in my version).

**Comment by SebastianStehle** [comment]
Test App Migrated

**Comment by laredoza** [comment]
Thanks, sorry I've got a tight deadline for today. Will have a look at the changes tomorrow.

**Comment by SebastianStehle** [comment]
Nice, would be nice to get a beta out to nuget tomorrow.

**Comment by SebastianStehle** [comment]
I Simplified the options and configuration extensions.

**Comment by laredoza** [comment]
It looks great. I'll continue going through it this weekend but I've posted a new preview package in the meantime:  https://www.nuget.org/packages/Orleans.Providers.MongoDB/2.0.0-preview1

**Comment by SebastianStehle** [comment]
Thank you: I also asked if we can use the icon: https://github.com/dotnet/orleans/issues/3660 ... minor thing, but would give the package an official touch :D

**Comment by laredoza** [comment]
yeah, that would be great. If you've got a nuget account please send it to me on gitter so that I can give you admin rights as well.

**Comment by SebastianStehle** [comment]
Orleans Team is fine when we use their icon. Can we finalize it? We should also make PR for the Orleans docs to add our link to the documentation.

**Comment by SebastianStehle** [comment]
I published a preview2
