### ISSUE TITLE
Cannot store integer default value (zero)

### ISSUE THREAD

**Issue by bluexo** [OrleansContrib/Orleans.Providers.MongoDB#30]
```
[Serializable]
public class SampleState
{
     public int SampleField { get; set } = 5
}
...

public async Task SampleGrainMethod()
{
     // Cannot store default integer value 
     // if the field exist in database , it will be remove   
      State.SampleField = 0 ;  
      await base.WriteStateAsync();
  }
```

**Comment by laredoza** [comment]
Hi,

With which version of the library are you experiencing this?

**Comment by bluexo** [comment]
@laredoza  vNext

**Comment by SebastianStehle** [comment]
I guess the problem are the json serializer settings. There is a setting to ignore default values. You can override this method and use your serializer settings:

https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/vNext/Orleans.Providers.MongoDB/StorageProviders/BaseJSONStorageProvider.cs#L157

**Comment by SebastianStehle** [comment]
It seems that the issue has been solved. Feel free to open it.
