### ISSUE TITLE
ISiloHostBuilder extension methods are present in MongoDBClientExtensions.cs

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/Orleans.Providers.MongoDB#34]
It seems extension methods intended for ISiloHostBuilder might have been accidentally copied into the file containing extension methods for IClientBuilder

![image](https://user-images.githubusercontent.com/1445862/37281158-7a863bfc-25c6-11e8-99d6-45969d838fc8.png)

![image](https://user-images.githubusercontent.com/1445862/37281195-927ae03c-25c6-11e8-8d54-f71c2f0fe4e3.png)

![image](https://user-images.githubusercontent.com/1445862/37281330-0f5a9c64-25c7-11e8-9d73-cc4b5a751936.png)

**Comment by SebastianStehle** [comment]
True, can you create a PR?

**Comment by bboyle1234** [comment]
Done :) All I did was delete the methods that looked like they didn't belong on the IClientBuilder.
