### ISSUE TITLE
Compatibility with Orleans 2.0.0-rc2

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/Orleans.Providers.MongoDB#36]
![image](https://user-images.githubusercontent.com/1445862/37323252-ec0151e4-2658-11e8-8246-4d3ea5187700.png)

**Comment by bboyle1234** [comment]
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/38

**Comment by SebastianStehle** [comment]
Thanks
