### ISSUE TITLE
About default values

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/Orleans.Providers.MongoDB#44]
A grain has its state object defined as shown below. `EventNumber` is a long.

![image](https://user-images.githubusercontent.com/1445862/41212822-3855e538-6d84-11e8-9100-a45d285d03b3.png)

The first time the grain is run, the field `DiscoveredPosition.EventNumber` is incremented to zero and the state is saved to mongodb.

This image, with an arrow pointer, shows that the data serialization has not specifically saved the value of `DiscoveredPosition.EventNumber` because it considers the value of `0` to be the default value. 

![image](https://user-images.githubusercontent.com/1445862/41212920-e21f2b74-6d84-11e8-8bef-d6e423d36d9e.png)

The next time the grain is run, the state is incorrectly rehydrated with `DiscoveredPosition.EventNumber` equal to -1.

What is the fix for this?

**Comment by SebastianStehle** [comment]
I don't get it. The value after deserialization will be also `0`, so where is the problem?

**Comment by bboyle1234** [comment]
Because of the way I've setup the initializer at -1, and because the "0" is missing from the serialized representation, the value after deserialization is -1, NOT 0

**Comment by bboyle1234** [comment]
The deserializer is leaving the field value untouched intead of adjusting it to 0

**Comment by bluexo** [comment]
@bboyle1234  #30

**Comment by bboyle1234** [comment]
https://docs.google.com/document/d/131a6quFOihOQyPEcipINIzb7XOVNTVALnGtScMneL9A/edit#

**Comment by SebastianStehle** [comment]
Just make a pull request for the current implementation ;)

**Comment by bboyle1234** [comment]
Hi @SebastianStehle :) Will there be a nuget release soon? I'd love to get this into production.

**Comment by SebastianStehle** [comment]
Done, should be available soon. I can also add you to the project if you want. I am not using the provider myself.

**Comment by bboyle1234** [comment]
Please add me to the project :) Thank you.
