### ISSUE TITLE
Not thread/interleave save?

### ISSUE THREAD

**Issue by Xanatus** [OrleansContrib/Orleans.Providers.MongoDB#46]
It seems when 2 calls end up in WriteStateAsync() on the same grain, there is a good chance that following InconsistentStateException is thrown:

![image](https://user-images.githubusercontent.com/20849443/41502332-e7b7aa6e-71fa-11e8-8801-9f6de9a49c6a.png)

This can easily happen on interleaved grains or when using timers (as seen in above screenshot).

I didn't try, but I assume an easy way to reproduce would be:
`Task.WhenAll(WriteStateAsync(), WriteStateAsync());`

**Comment by SebastianStehle** [comment]
Thats by design: https://dotnet.github.io/orleans/Documentation/Core-Features/Grain-Persistence.html#storage-provider-semantics

**Comment by Xanatus** [comment]
Why is this by design and why can it not be prevented?
Cueing up the queries not an option?

It used to work fine in 1.5.
If stateful grains can no longer use interleave semantics, this should be documented better. I can also see performance drops in my application due to this.

**Comment by SebastianStehle** [comment]
You already have an option for queuing: Do not use interleaving ;)

There might be a bug in the implementation, but  it is important to follow the official semantics. If you have 2 concurrent calls making changes to a state you can have concurrency issues anyway.

**Comment by Xanatus** [comment]
Interleaving is not concurrent and there can be valid reasons to do it that way.
And its sometimes just hard to work around it. Such as that orleans timers enforces it.
And sure, knowing this restriction makes it of course possible to avoid it. Unfortunately I didn't know about it before 2.0 when etags where not a thing and refactoring this is a bitch now.

But anyway, do you think the following is save to use when not caring about consistency?

```
Task WriteStateAsyncNoConsistencyCheck()
{
   try
   {
      return WriteStateAsync();
   }
   catch (InconsistentStateException)
   {
      return WriteStateAsyncNoConsistancyCheck();
   }
}
```

**Comment by SebastianStehle** [comment]
Thats true with concurrency. I just think it is the wrong place to discuss it. All orleans storage provider should follow the same semantics. If you want to avoid it you can just implement your own storage mechanism. Personally I also do not use Orleans Storage because I have different requirements.
