### ISSUE TITLE
How to customize DateTime value's storage format?

### ISSUE THREAD

**Issue by sdghchj** [OrleansContrib/Orleans.Providers.MongoDB#47]
` public class JsonGrainStateSerializer : IGrainStateSerializer
    {
        private readonly JsonSerializer serializer;

        public JsonGrainStateSerializer(ITypeResolver typeResolver, IGrainFactory grainFactory)
            : this(JsonSerializer.Create(OrleansJsonSerializer.GetDefaultSerializerSettings(typeResolver, grainFactory)))
        {
        }
        .....
}`

public class JsonSerializerSettings
{
        ......
        internal const string DefaultDateFormatString = @"yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";
        ......
}

As the DefaultSerializerSettings is used to construct JsonGrainStateSerializer , so the the DefaultDateFormatString is also used to serialize DateTime members of a grain state. I am now using MongoDB as the storage database, however a DateTime type value is stored as string type while I want it to be DateTime type in MongoDB. I found there is no way I can change its format in my orleans based project.

**Comment by SebastianStehle** [comment]
The issue is here:

https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/master/Orleans.Providers.MongoDB/StorageProviders/JsonBsonConverter.cs#L85

**Comment by sdghchj** [comment]
Thank you. I fork your project and  modifed the DateTime type's serialization. Please check the pull request.

**Comment by sdghchj** [comment]
over
