### ISSUE TITLE
CollectionPrefix mismatch

### ISSUE THREAD

**Issue by bboyle1234** [OrleansContrib/Orleans.Providers.MongoDB#54]
The following image shows the two configuration options classes that are used for Orleans membership. 

On the left, `MongoDBGatewayListProviderOptions` is used by the `IClusterClientBuilder` and sets the default `CollectionPrefix` value to `Members`.

On the right, `MongoDBMembershipTableOptions` is used by the `ISiloHostBuilder` extension methods and sets the default `CollectionPrefix` value to `null`.

The consequence is that unless users explicitly set the `CollectionPrefix` value when initializing both the silo and the client, there will be an accidental collection name mismatch, as shown in the second image below: 

![image](https://user-images.githubusercontent.com/1445862/46327546-7dc67000-c645-11e8-9845-1eec62fed97f.png)

![image](https://user-images.githubusercontent.com/1445862/46327622-fc231200-c645-11e8-8836-c3461bf77189.png)

The solution as I see it is to initialize the default `CollectionPrefix` value in the base class inherited by both, `MongoDBOptions.CollectionPrefix`.

I think the best default for this value is `null`. What do you think?

**Comment by SebastianStehle** [comment]
Finally merged.
