### ISSUE TITLE
With mongodb's Reminders, silents will not be executed after Silo restarts.

### ISSUE THREAD

**Issue by AClumsy** [OrleansContrib/Orleans.Providers.MongoDB#57]
With mongodb's Reminders, silents will not be executed after Silo restarts. It can still be executed after restarting Silo using Microsoft.Orleans.Reminders.AdoNet.

Orleans   : V2.1.1
Orleans.Providers.MongoDB ：V2.0.0

DEMO：
[Orleans.Reminder.zip](https://github.com/OrleansContrib/Orleans.Providers.MongoDB/files/2588124/Orleans.Reminder.zip)

**Comment by zh6335901** [comment]
I also have this problem. I found if silo shutdown before a reminder's **StartAt** time, Then start after this reminder's **StartAt** time, This reminder will not be executed.

PS: I try remove this reminder document in the mongodb, then restart silo, this reminder is work again.

**Comment by SebastianStehle** [comment]
Sorry for the very long delay. Do you have an idea what the problem could be?

**Comment by SebastianStehle** [comment]
I was able to reproduce it and have fixed it.
