### ISSUE TITLE
2 different collections generated

### ISSUE THREAD

**Issue by JanWilczak** [OrleansContrib/Orleans.Providers.MongoDB#58]
When using from both client and the silo there are 2 different collections generated: 
`MembersOrleansMembershipV2` and `OrleansMembershipV2`
Temporary solution is to specify `CollectionPrefix` in `UseMongoDbClustering`.

package Orleans.Providers.MongoDB 2.0.2

**Comment by matteofabbri** [comment]
yep same bug i was here to open

**Comment by SebastianStehle** [comment]
Fix by PR: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/55

Will be released soon.
