### ISSUE TITLE
port to netcore + orleans 2?

### ISSUE THREAD

**Issue by stephenlautier** [OrleansContrib/Orleans.Providers.MongoDB#6]
Hi,

I'm quite interested in using this, will you be porting this to .netcore / orleans 2 preview?

Thanks

**Comment by laredoza** [comment]
Hi,

My apologies for only getting back to you now.

I will definitely be porting the providers to core but I'm waiting for orleans 2 to be more stable /settled. From what I can see the Mongo drivers are already core compatible, so this shouldn't be too difficult.

Regards

**Comment by stephenlautier** [comment]
@laredoza it's not a problem. That's great thanks!

**Comment by galvesribeiro** [comment]
@laredoza you can easily have a build with conditional references. So if targeting `net461`, use the reference from nuget.org, othewise, use the one from myget. It is stable enough.

**Comment by laredoza** [comment]
@galvesribeiro Thanks, I will have a look at it. Just a bit tight on time at the moment. I'll probably only get a chance to look at it in July or so.

**Comment by fschuh** [comment]
I have tested this on Orleans 2.0 preview and .Net Core and can confirm it works with no modifications to the code.
I just recreated the project from scratch (new csproj format), pointed to the orleans 2.0 preview dependencies on MyGet and it just worked.
I haven't tried any Unit Tests, just the main DLL.

Good news when the time comes to update this package :)

**Comment by laredoza** [comment]
@fschuh that's great news. I should be able to start working on this pretty soon.

**Comment by laredoza** [comment]
I've merged @leisurelyclouds pr and the test application is working. Which is good news. 

There are two minor issues at the moment. 

- The Build.bat file isn't working properly.
- The UnitTest project isn't running at the moment (I'm disabling the project at the moment).

I'll look at these this weekend.

Thanks again @leisurelyclouds

**Comment by laredoza** [comment]
After installing dotnet core sdk 2.0 the UnitTest project is running.

**Comment by laredoza** [comment]
Uploaded a preview package:

https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.2-preview

**Comment by laredoza** [comment]
Published a new package:
https://www.nuget.org/packages/Orleans.Providers.MongoDB/0.1.2
