### ISSUE TITLE
README : Broken link

### ISSUE THREAD

**Issue by Abhith** [OrleansContrib/Orleans.Providers.MongoDB#60]
In the root **README.md**, there is some `rc1` branch mentioned with link which does not exist.

> Please see the rc1 branch for the new Orleans 2 rc1 implementation (https://github.com/OrleansContrib/Orleans.Providers.MongoDB/tree/rc1)

**Comment by SebastianStehle** [comment]
Thanks the MongoDB provider is 2.0 ready since the RTM of Orleans 2.
