### ISSUE TITLE
Number of open connections

### ISSUE THREAD

**Issue by vella-nicholas** [OrleansContrib/Orleans.Providers.MongoDB#61]
Am I right to understand that the number of open simultaneous connections is set only from the connection string? 

If I load hundreds of grains at once, will every initialization try and open a connection per initialization unless I set up a connection limit in the connection string?

**Comment by SebastianStehle** [comment]
No, there is a default value: https://docs.mongodb.com/v3.6/reference/connection-string/#connection-pool-options

**Comment by vella-nicholas** [comment]
Ok thanks!
