### ISSUE TITLE
Seems that the gateways marked as dead did not been removed in time

### ISSUE THREAD

**Issue by Jame6292** [OrleansContrib/Orleans.Providers.MongoDB#70]
I received these warnings when i close my silos.
`warn: Orleans.Messaging.GatewayManager[101321]
      All gateways have previously been marked as dead. Clearing the list of dead gateways to expedite reconnection.
`

So i guess `Orleans.Providers.MongoDB` did not  remove dead gateways in time.
Of course, these gateway documents still existed in the collection OrleansMembershipV2

I hope this can be fixed in next release. 

Thank you.

**Comment by SebastianStehle** [comment]
So far there is no automatic cleanup in Orleans 2.X I think. The interface has been introduced with 3.0 or am I wrong?

**Comment by Jame6292** [comment]
Hi,
Thanks for your reply. 

Now I'm using `Orleans 3.0 rc2` . I didn't find any warnings like this in Orleans 2.X.

So, I think the "cleanup" feature came from 3.0.

**Comment by SebastianStehle** [comment]
Yes, it is this method: https://github.com/dotnet/orleans/search?q=CleanupDefunctSiloEntries&unscoped_q=CleanupDefunctSiloEntries

As you can see, even the support in Orleans itself is not so good. I will implement it as soon as 3.0 is out, I wait to migrate my application as well and Orleans is the last bit.

**Comment by Jame6292** [comment]
Yes, most of them are `Not Implemented`.
 
 I guess they will be implemented in Orleans 3.0 release. 

Thank you very much.

**Comment by jurby** [comment]
> [3.0.0-rc2] (changes since 3.0.0-rc1)
> Non-breaking improvements
> 
> Default to cleaning up dead silo entries in the cluster membership table after 7 days. (#6032)

https://github.com/dotnet/orleans/blob/4d92fce6a4d5b2910c204c0269fd6d9c58394654/changelog.

**Comment by SebastianStehle** [comment]
I know.

**Comment by SebastianStehle** [comment]
Done and deployed to nuget as 3.0

**Comment by Jame6292** [comment]
I'm really very much appreciate your help
