### ISSUE TITLE
Clustering: support extended membership protocol

### ISSUE THREAD

**Issue by ReubenBond** [OrleansContrib/Orleans.Providers.MongoDB#71]
The current implementation of this clustering provider only supports the initial membership protocol, not the later [extension to the protocol](https://dotnet.github.io/orleans/Documentation/implementation/cluster_management.html#extension-to-totally-order-membership-views) to support totally ordered views of cluster membership.

It's important to support this so that the provider will function correctly.

See this PR which adds such support to Consul: https://github.com/dotnet/orleans/pull/6095

**Comment by SebastianStehle** [comment]
Done in this big PR: https://github.com/OrleansContrib/Orleans.Providers.MongoDB/pull/72

**Comment by SebastianStehle** [comment]
Solved with 2 different approaches.

**Comment by ReubenBond** [comment]
Very quick turnaround, @SebastianStehle - the result looks great!

**Comment by SebastianStehle** [comment]
Thx, I need it myself, I am using the provider in production and the rolling deployment is a little bit jolty and I am not sure yet, what the reason is.
