### ISSUE TITLE
AddMongoDBGrainStorage

### ISSUE THREAD

**Issue by cwoodall-arch** [OrleansContrib/Orleans.Providers.MongoDB#75]
This is probably related to the breaking change, but I can't seem to resolve the issue. My silo works fine without AddMongoDBGrainStorage, but it fails with the following error when I add it:

> Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Providers.MongoDB.Configuration.MongoDBGrainStorageOptions]' from root provider.

Here is my silo if it helps:

> public static IHostBuilder CreateOrleansMongoHost(string[] args) =>

            Host.CreateDefaultBuilder(args)
            .UseOrleans((host, config) =>
            {
                config.UseMongoDBClient(host.Configuration.GetSection("MongoStorage").Value)
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "TestCluster";
                    options.ServiceId = "TestService";
                })
                .UseMongoDBClustering(options =>
                {
                    options.DatabaseName = "Test";
                    options.Strategy = MongoDBMembershipStrategy.SingleDocument;
                })
                .UseMongoDBReminders(options =>
                {
                    options.DatabaseName = "Test";
                })
                .AddMongoDBGrainStorage("TestStore", options =>
                {
                    options.DatabaseName = "Test";
                    options.CreateShardKeyForCosmos = false;
                    options.ConfigureJsonSerializerSettings = settings =>
                    {
                        settings.NullValueHandling = NullValueHandling.Include;
                        settings.ObjectCreationHandling = ObjectCreationHandling.Replace;
                        settings.DefaultValueHandling = DefaultValueHandling.Populate;
                    };
                })
                .ConfigureEndpoints(Dns.GetHostName(), 11111, 30000)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(ITestGrain).Assembly).WithReferences());
            })
            .ConfigureWebHostDefaults(config =>
            {
                config.UseStartup<Startup>();
            })
            .ConfigureLogging(config =>
            {
                config.AddConsole();
            });

**Comment by SebastianStehle** [comment]
Perhaps an issue with the custom name "TestStore"? Have you tried the "asDefault" variant?

**Comment by cwoodall-arch** [comment]
Hi. I just tried using the AddMongoDBGrainStorageasDefault method, and I get the same result.

**Comment by SebastianStehle** [comment]
I cannot reproduce it, I need a sample

**Comment by GundamBox** [comment]
It works fine in localhost, but got the same exception in Azure Cosmos DB

> System.InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[Orleans.Providers.MongoDB.Configuration.MongoDBGrainStorageOptions]' from root provider.

Then I found this [issue](https://github.com/dotnet/orleans/issues/5543), so I clone the source code and replace `IOptionsSnapshot` to `IOptionsMonitor`, and it just works.

PS. English is not my native language.

**Comment by ReubenBond** [comment]
Yes, it should be the same fix as here: https://github.com/OrleansContrib/Orleans.CosmosDB/pull/43/files

@GundamBox, could you submit a PR?
