### ISSUE TITLE
WriteLogStatisticsToTable="false" is not working

### ISSUE THREAD

**Issue by AwsomeCode** [OrleansContrib/Orleans.Providers.MongoDB#8]
I am getting documents in my OrleansStatisticsCollection.

**Comment by laredoza** [comment]
@AwsomeCode Busy investigating

**Comment by laredoza** [comment]
Hi @AwsomeCode, sorry that I only got to this now.

It's a configuration error. Just add 

<Statistics ProviderType="MongoStatisticsPublisher" WriteLogStatisticsToTable="false" />

to the ClientConfiguration.xml file

**Comment by AwsomeCode** [comment]
@laredoza Thanks.
