### ISSUE TITLE
Does options.CreateShardKeyForCosmos work on on-premise MongoDB?

### ISSUE THREAD

**Issue by vrecluse** [OrleansContrib/Orleans.Providers.MongoDB#95]
Or only Cosmos is supported?

**Comment by SebastianStehle** [comment]
Yes

**Comment by vrecluse** [comment]
> Yes

To the title or comment?

**Comment by SebastianStehle** [comment]
Sorry, it has been only tested for cosmos DB I think, because you need a shared key in cosmos. But I do not use it myself.
