### ISSUE TITLE
CreateShardKeyForCosmos does not create sharded collection

### ISSUE THREAD

**Issue by tomhreb** [OrleansContrib/Orleans.Providers.MongoDB#98]
Hello,
I think that the method ```GetCollection``` -> 
https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/84a3237dbfb6f6510ca2ed954304d7871ee3edb7/Orleans.Providers.MongoDB/StorageProviders/MongoGrainStorage.cs#L193-L200

is missing specification of shard key as for CosmsoDB as per the [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb/custom-commands#create-a-sharded-collection) / it has to be created differently for CosmosDB.

Creating a collection via command below creates the collection really sharded, at least according to Azure Monitor.
```
db.createCollection(<collectionName>, {
    "shardKey": "_id",
    "indexes": [{key: {_id: 1}}}]
});
```

**Comment by SebastianStehle** [comment]
Could be, not a CosmosDB user. PRs are welcome ;)

**Comment by tomhreb** [comment]
Great :) See PR #99
